config/routes.rb
Rails.application.routes.draw do
  
#  mount Ckeditor::Engine => '/ckeditor'
  mount LoldesignPublisher::Rails::Engine => '/'
  
  devise_for :admin, path_names: {
                                   sign_in: 'entrar',
                                   sign_out: 'sair'
                                 }

  devise_for :user, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }

  devise_for :customer, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }
  
                                        
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :cities, only: [:index] 


  namespace :admin do 

    resources :customers do
      collection do
        get :filters
      end
    end

    resources :booking_policies do
      collection do
        get :filters
      end
    end

    resources :rooms do
      collection do
        get :filters
      end
    end

    resources :occupations do
      collection do
        get :filters
      end
    end

    resources :accommodation_sizes do
      collection do
        get :filters
      end
    end

    resources :type_terms do
      collection do
        get :filters
      end
    end

    resources :terms do
      collection do
        get :filters
      end
    end

    resources :establishment_terms do
      collection do
        get :filters
      end
    end

    resources :type_attractions do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    
    resources :admins do
      collection do
        get :filters
      end
    end

    resources :commforts do
      collection do
        get :filters
      end
    end

    resources :price_ranges do
      collection do
        get :filters
      end
    end

    resources :payment_types do
      collection do
        get :filters
      end
    end
    resources :lodgings do
      collection do
        get :filters
      end
    end
    resources :services do
      collection do
        get :filters
      end
    end
    resources :accommodation_items do
      collection do
        get :filters
      end
    end
    resources :accommodation_types do
      collection do
        get :filters
      end
    end
    resources :environments do
      collection do
        get :filters
      end
    end
    resources :recreation_areas do
      collection do
        get :filters
      end
    end
    resources :rules do
      collection do
        get :filters
      end
    end
    resources :social_items do
      collection do
        get :filters
      end
    end

    resources :enterprises do
      collection do
        get :filters
      end
    end

    resources :structures do
      collection do
        get :filters
      end
    end


    resources :environments do
      collection do
        get :filters
      end
    end    

    resources :form_payments do
      collection do
        get :filters
      end
    end

    resources :recreation_areas do
      collection do
        get :filters
      end
    end

    resources :rules do
      collection do
        get :filters
      end
    end

    resources :services do
      collection do
        get :filters
      end
    end

    resources :social_items do
      collection do
        get :filters
      end
    end   

    resources :structures do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    resources :icons do
      collection do
        get :filters
      end
    end

    resources :furnitures do
      collection do
        get :furnitures
      end
    end

    resources :business_establishments do
      collection do
        get :filters
      end
    end

    resources :establishment_categories do
      collection do
        get :filters
      end
    
    end


    root :to => "services#index"

  end


  namespace :user do

    resources :chefs do
      collection do
        get :filters
      end
    end

    

    resources :restaurants do
      collection do
        get :filters
        get 'country'
      end
    end
    resources :restaurant_surveys do
      collection do
        get :filters
      end
    end

    
    resources :publications do
      collection do
        get :filters
      end
    end
    resources :establishments do
      collection do
        get :filters
        get 'city'
        get 'country'
        post 'address-infos'    , to: 'establishments#address_infos', as: :address_infos

      end
    end
    
    resources :main_courses do
      collection do
        get :filters
      end
    end    

    resources :users do
      collection do
        get :filters
      end
    end 
    resources :specialities do
      collection do
        get :filters
      end
    end   
    resources :tourist_attractions do
      collection do
        get :filters
        get 'country'
      end
    end   

    resources :tourist_attraction_surveys do
      collection do
        get :filters
      end
    end      

    resources :hotels do
      collection do
        get :filters
        get 'city'
        get 'country'
      end
    end       

    resources :hotel_surveys do
      collection do
        get :filters
      end
    end  

    resources :cities do 
      collection do
        get :filters
      end
    end


    root :to => "hotels#index"


  end

  namespace :customer do 
    resources :profiles, except: [:index, :new]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	
before_action :load_user, only: [:show, :destroy, :edit, :update]
before_action :load_filter_fields, only: [:index, :filters]
	

  def index
    @users = User.all.order('email').page(params[:page] || 1).per_page(30)
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_users_path, notice: 'Criado com sucesso'
    else
      render action: :new
    end
  end

  def edit
    
  end

  def show
    @user = User.find(params[:id])
  end


  def update

    if params[:user][:password].present?
      if @user.update(user_params_without_password)
        redirect_to user_users_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit
      end        
    elsif params[:user][:profile_id].present?
      if @user.update_attributes(user_params_without_profile)
        redirect_to user_users_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit
      end
    else
      if @user.update_attributes(user_params)
        redirect_to user_users_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit
      end
    end

  end

  def destroy
    @user.destroy

    redirect_to user_users_path, notice: 'Removido com sucesso'
  end


  def filters
    @users = User.order(created_at: :desc)
    @users = process_filters(params, @users) if params[:query].present?

    respond_to do |format|
      format.html do 
        @users = @users.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :email, type: :common},
    ]
  end

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params
      .require(:user)
      .permit(
        :email,
        :password,
        :password_confirmation,
        :name,
        :phone_number,
        :photo
      )
  end

  def user_params_without_password
    params
      .require(:user)
      .permit(
        :email,
        :name,
        :phone_number,
        :photo
      )
  end

  def user_params_without_profile
    params
      .require(:user)
      .permit(
        :email,
        :password,
        :password_confirmation,
        :name,
        :phone_number,
        :photo     
      )
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  layout "reporter"
  before_action :authenticate_user!
  

  def authenticated_user
    current_user
  end

   
 def process_filters(params, resources)
    @resources = resources

    filters_groups = @filters_arr.group_by{ |filter| filter[:type] }
    filter_by_type filters_groups

    @resources
  end

  def filter_by_type filter
    filter_commons  filter[:common] if filter[:common].present?
    filter_nesteds  filter[:nested] if filter[:nested].present?
    filter_commons  filter[:select] if filter[:select].present?
    filter_dates    filter[:date]   if filter[:date].present?
    filter_floats   filter[:float]  if filter[:float].present?
  end

  def filter_commons commons
    commons.each do |common|
      @resources = @resources.where("LOWER (#{common[:attr].to_s}) LIKE LOWER(?)"  , "%#{params[:query][common[:attr]]}%") if params[:query][common[:attr]].present?      
    end 
  end

  def filter_dates dates
    dates.each do |date|
      @resources = @resources.where(date[:attr] => [params[:query][date[:attr]][:from].to_date.beginning_of_day..params[:query][date[:attr]][:to].to_date.end_of_day]) if params[:query][date[:attr]].present? && params[:query][date[:attr]][:to].present? && params[:query][date[:attr]][:from].present?
    end
  end

  def filter_nesteds nesteds
    nesteds.each do |nested|
      @resources = @resources.joins(nested[:nested_class]).where("LOWER(#{nested[:nested_class].to_s.pluralize}.#{nested[:nested_attr]}) LIKE LOWER(?)", "%#{params[:query][nested[:attr]]}%") if params[:query][nested[:attr]].present?
    end
  end

  def filter_floats floats
    floats.each do |float|
      @resources = @resources.where(float[:attr] => params[:query][float[:attr]].to_f) if params[:query][float[:attr]].present?
    end
  end

end

app/controllers/user/chefs_controller.rb
class User::ChefsController < User::BaseController

  before_action :load_chef, only: [:show, :destroy, :edit, :update]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @chefs = Chef.all.order('name').page(params[:page] || 1).per_page(30)
  end


  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)

    if @chef.save
      redirect_to user_chefs_path, notice: "Registro #{@chef.name} Criado com sucesso"
    else
      render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
    end
  end

  def edit
    
  end

  def show
    @chef = Chef.find(params[:id])
  end


  def update
    if @chef.update_attributes(chef_params)
       @chef = Chef.find(params[:id])
      redirect_to user_chefs_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @chef.active = false
    if @chef.save
       redirect_to user_chefs_path, notice: 'Registro desativado com sucesso'
    end
  end
  def filters
    @chefs  = Chef.order(created_at: :desc)
    @chefs  = process_filters(params, @chefs ) if params[:query].present?

    respond_to do |format|
      format.html do 
        @chefs  = @chefs.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :name, type: :common},
    ]
  end


  
  def load_chef
    @chef = Chef.find(params[:id])
  end

  def chef_params
    params
      .require(:chef)
      .permit(
        :name,
        :active,
        :description,
        :service_time,
        main_courses:[],
        photos:[],
        videos: [],
      )
  end
end

app/controllers/user/cities_controller.rb
class User::CitiesController < User::BaseController

  before_action :load_city, only: [:show, :destroy, :edit, :update]
  before_action :load_hotels, only: [:index, :filters]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @cities = City.order(:created_at).page(params[:page] || 1).per_page(30)
    
  end


  def new
    @city = City.new
    @city.build_establishment

  end

  def create
    @city = City.new(city_params)

    createCityManager = EstablishmentsManager.new()
    city_existes = createCityManager.process(@city.country, @city.state, @city.city, "validate")

    if @city.save && !city_existes
      redirect_to user_cities_path, notice: "Registro Criado com sucesso"
    else
      if city_existes
        redirect_to user_cities_path, notice: 'A cidade já está cadatrado.'
      else
        render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
      end 
    end
  end

  def edit

  end

  def show
    city = City.find(params[:id])
  end


  def update

    if @city.update_attributes(city_params)
      redirect_to user_cities_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @city.active = false
    if @city.save
     redirect_to user_cities_path, notice: 'Registro desativado com sucesso'
   end
 end
 def filters
  @cities  = City.order(created_at: :desc)
  @cities  = process_filters(params, @cities ) if params[:query].present?

  respond_to do |format|
    format.html do 
      @cities  = @cities.page(params[:page] || 1).per_page(30)
      render :index
    end
  end
end

private

def load_city
  @city = City.find(params[:id])
end

def load_filter_fields
  @filters_arr = [
    {attr: :city, type: :common},    
    {attr: :state, type: :common},
    {attr: :country, type: :common},
    {attr: :biome, type: :common},
    {attr: :region, type: :common},
  ]
end

def load_hotels
  
end

def load_restaurants

end
def load_touristattractions

end


def city_params
  params
  .require(:city)
  .permit(
    :text_apresentation,
    :best_time,
    :how_find,
    :city,
    :state,
    :country,
    :biome,
    :perfect_day,
    :special,
    :perfect_day_remarks,
    :region,
    :establishment_id,
    :best_experiences,
    differentials:[],
    photos:[],
    videos: [],
    documents: [], 
    establishment_attributes: [
      :id,
      :name,
      :active,
      :environment,
      :neighborhood,
      :comfort_classification,
      :final_comment,
      :contact,
      :email,
      :address,
      :cep,
      :street,
      :complement,
      :number_address,
      :city,
      :state,
      :nationality,
      :final_note,
      :geolocalization,
      :reference_point,
      :owner,
      :telephone,
      :reservation_phone,
      :comments,
      :business_establishment,
      :facebook,
      :linkedin,
      :twitter,
      :instagram,
      :website],
      )
end
end

app/controllers/user/establishments_controller.rb
class User::EstablishmentsController < User::BaseController
  before_action :load_establishment, except: [:address_infos, :destroy]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @establishments = Establishment.all.order('updated_at').page(params[:page] || 1).per_page(30)
  end


  def new
    @establishment = Establishment.new
  end

  def create
    @establishment = Establishment.new(establishment_params)

    if @establishment.save

      redirect_to user_establishments_path, notice: "Registro #{@establishment.name} Criado com sucesso"
    else
      render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
    end
  end

  def edit
    
  end

  def show
    @establishment = Establishment.find(params[:id])
  end


  def update
    
    if @establishment.update_attributes(establishment_params)
      
      redirect_to user_establishments_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @establishment.active = false
    if @establishment.save
      
      redirect_to user_establishments_path, notice: 'Registro desativado com sucesso'
    end
  end

  def address_infos
    manager = CepManager.new(params[:cep])

    begin
      manager = manager.process
      render status: 200, json: manager.to_json
    rescue
      render status: 422
    end
  end


  def filters
    @establishments  = Establishment.order(created_at: :desc)
    @establishments  = process_filters(params, @establishments ) if params[:query].present?

    respond_to do |format|
      format.html do 
        @establishments  = @establishments.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :name, type: :common},
    ]
  end


  
  def load_establishment
    @establishment = Establishment.find(params[:id])
  end

  def establishment_params
    params
      .require(:establishment)
      .permit(
        :name,
        :active,
        :environment,
        :comfort_classification,
        :final_comment,
        :contact,
        :email,
        :address,
        :cep,
        :street,
        :complement,
        :number_address,
        :city,
        :state,
        :nationality,
        :final_note,
        :geolocalization,
        :reference_point,
        :owner,
        :telephone,
        :reservation_phone,
        :comments,
        :facebook,
        :linkedin,
        :twitter,
        :instagram,
        :website,
        business_establishment: [],
      )
  end
end
require 'correios-cep'

app/controllers/user/home_controller.rb
class User::HomeController < User::BaseController

	def index
		
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/user/tourist_attraction_surveys/_adventure_tourism.html.erb
<div class="row form-group">
	<div class="col-md-3">
		<%= f.input :adventure_tourism_score %>
	</div>
		<div class="col-md-9">
		<%= f.input :adventure_tourism_score_comments, class: "form-control" %>
	</div>
</div>

app/views/user/tourist_attraction_surveys/_beach_tents.html.erb
<div class="row form-group">
	<div class="col-md-3">
		<%= f.input :beach_tents_score %>
	</div>
		<div class="col-md-9">
		<%= f.input :beach_tents_score_comments, class: "form-control" %>
	</div>
</div>

app/views/user/tourist_attraction_surveys/_events.html.erb
<div class="row form-group">
	<div class="col-md-3">
		<%= f.input :events_score %>
	</div>
		<div class="col-md-9">
		<%= f.input :events_score_comments, class: "form-control" %>
	</div>
</div>

app/views/user/tourist_attraction_surveys/_form.html.erb
<!-- NOVO / EDICAO -->
<%= simple_form_for [:user, @tourist_attraction_survey]  do |f|%>
  <%= f.error_notification %>
  

    <% if @tourist_attraction_survey.errors.any? %>
      <div id="error_explanation">
        <ul>
        <% @tourist_attraction_survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div> 
      <% if !f.object.tourist_attraction_id.present? %>
        <!-- Novo -->
        <%= f.hidden_field :tourist_attraction_id, value: params[:tourist_attraction_id] %>
      <% end %>	
    </div>
Novo/ EDICAO
    <div class="container-md">
        <div class="card">
        <% if !f.object.tourist_attraction_id.present? %>
        NOVO<div class="card-header"><strong>Avaliação da Atração Turística</strong></div>
        <% else %>
			  <div class="card-header"><strong>Avaliação da Atração Turística -  <%= TouristAttraction.find(params[:tourist_attraction_id].present? ? params[:tourist_attraction_id] : f.object.tourist_attraction_id).establishment.name %></strong></div>
        

        <% end %>

		    <div class="card-body">
          <div class="row form-group">
            <div class="col-md-3">
              <%= f.input :active  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-3">
              <%= f.label :survey_date, class: "col-form-label" %>:

              <% if f.object.survey_date.present? %>
              <%= f.date_field :survey_date , class: "form-control datepicker", type: "date" , required: :true %>
              <% else %>
              <%= f.text_field :survey_date , class: "form-control datepicker", type: "date" , required: :true%>
              <% end %>
            </div>
          </div>
         
          <%= render partial: 'signage', locals: {f: f}  %>
          <%= render partial: 'conservation', locals: {f: f}  %>
          <%= render partial: 'accessibility', locals: {f: f}  %>
          <%= render partial: 'local_tour_guides', locals: {f: f}  %>																
          <%= render partial: 'kindness', locals: {f: f}  %>
          <%= render partial: 'beauty', locals: {f: f}  %>
          <%= render partial: 'infrastructure', locals: {f: f}  %>
          <%= render partial: 'historical_importance', locals: {f: f}  %>																
          <%= render partial: 'artistic_importance', locals: {f: f}  %>
          <%= render partial: 'architectural_importance', locals: {f: f}  %>
          <%= render partial: 'natural_importance', locals: {f: f}  %>
          <%= render partial: 'cultural_importance', locals: {f: f}  %>																
          <%= render partial: 'economic_importance', locals: {f: f}  %>
          <%= render partial: 'interest', locals: {f: f}  %>
          <%= render partial: 'sort_order_by_destination', locals: {f: f}  %>
          <%= render partial: 'shopping', locals: {f: f}  %>
          <%= render partial: 'events', locals: {f: f}  %>
          <%= render partial: 'cultural_centers', locals: {f: f}  %>
          <%= render partial: 'historical_buildings', locals: {f: f}  %>
          <%= render partial: 'strong', locals: {f: f}  %>
          <%= render partial: 'churches', locals: {f: f}  %>
          <%= render partial: 'museums', locals: {f: f}  %>
          <%= render partial: 'parks', locals: {f: f}  %>
          <%= render partial: 'state_parks', locals: {f: f}  %>
          <%= render partial: 'national_parks', locals: {f: f}  %>
          <%= render partial: 'thematic_parks', locals: {f: f}  %>
          <%= render partial: 'tours', locals: {f: f}  %>
          <%= render partial: 'beaches', locals: {f: f}  %>
          <%= render partial: 'beach_tents', locals: {f: f}  %>
          <%= render partial: 'adventure_tourism', locals: {f: f}  %>         
          <%= render partial: 'final', locals: {f: f}  %>
        </div>
		</div>
    
    <div class="card-footer">
		  <%= button_tag(type: "submit", class: "btn btn-sm btn-success", disable_with: "gravando...") do %>
		  <i class="fas fa-cloud-upload-alt"></i> Salvar
      <% end %>
      
      <% if !f.object.tourist_attraction_id.present? %>
      <!--novo  --> 
      <%= link_to raw('<i class="far fa-window-close"></i> Cancelar'), user_tourist_attraction_surveys_path(tourist_attraction_id:  params[:tourist_attraction_id]), class: "btn btn-sm btn-danger" %>  
      
      <% else %>
      <!--edicao  --> 
      <%= link_to raw('<i class="far fa-window-close"></i> Cancelar'), user_tourist_attraction_surveys_path(tourist_attraction_id: f.object.tourist_attraction_id), class: "btn btn-sm btn-danger" %>  
    <% end %>	
      


		</div>
<% end %>

app/views/user/tourist_attraction_surveys/_tourist_attraction_survey.html.erb
<tr>
  <td><%= tourist_attraction_survey.survey_date %></td>
	<td><%= tourist_attraction_survey.final_comments %></td>
	<td><%= tourist_attraction_survey.final_rate %></td>
	<td><%= tourist_attraction_survey.active %></td>
	<td>
  <%= link_to raw('<i class="fas fa-eye" style="color:green"></i>'), user_tourist_attraction_survey_path(id: tourist_attraction_survey.id)  %>
  <%= link_to raw('<i class="fas fa-edit style="color:blue"></i>'), edit_user_tourist_attraction_survey_path(id: tourist_attraction_survey.id) %>
  <%= link_to raw('<i class="fas fa-times" style="color:red"></i>'), user_tourist_attraction_survey_path(tourist_attraction_survey), method: :delete, data: { confirm: 'Are you sure?' } %>
</td>
</tr>

app/views/user/tourist_attraction_surveys/index.html.erb
<div class="card">
  <div class="card-header">
    <strong> Avaliações da Atração Turistica - <%= TouristAttraction.find(params[:tourist_attraction_id].present? ? params[:tourist_attraction_id] : f.object.tourist_attraction_id).establishment.name %></strong>
    
    </div>
  <div class="card-body">
    <div class="form-group">
    <%= render partial: 'layouts/filters/filters', locals: { path: filters_user_tourist_attraction_surveys_path, resource: TouristAttractionSurvey } %>
    </div>  
    <table class="table table-responsive-sm table-striped">
      <thead>
        <tr>
          <th>
            <%= TouristAttractionSurvey.human_attribute_name(:survey_date) %>
          </th>
          <th>
            <%= TouristAttractionSurvey.human_attribute_name(:final_comments) %>
          </th>
          <th>
            <%= TouristAttractionSurvey.human_attribute_name(:final_rate) %>
          </th>
          <th>
           <%= TouristAttractionSurvey.human_attribute_name(:active) %>
          </th>
          <th>
          -
          </th>
        </tr>
      </thead>
      <tbody>
          <%= display_list_for(@tourist_attraction_surveys, fields: 5) %>
      </tbody>
    </table>      
  </div>
  <div class="card-footer"><%= will_paginate @tourist_attraction_surveys %></div>
</div>

app/views/user/tourist_attraction_surveys/show.html.erb
<!-- VIEW -->
<%= simple_form_for [:user, @tourist_attraction_survey] do |f|%>
VIEW
  <div class="container-md">
     <div class="card">
      <div class="card-header">
        <strong> Avaliação da Atração Turística - 
                                   
        <%= TouristAttraction.find( f.object.tourist_attraction_id).establishment.name %></strong>
      </div>

      <div class="card-body">
      <div class="row form-group">
        <div class="col-md-3">
          <%= f.input :active  %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :survey_date, class: "col-form-label" %>:

          <% if f.object.survey_date.present? %>
          <%= f.date_field :survey_date , class: "form-control datepicker", type: "date" %>
          <% else %>
          <%= f.text_field :survey_date , class: "form-control datepicker", type: "date" %>
          <% end %>
        </div>
      </div>

        <%= render partial: 'user/tourist_attraction_surveys/show/signage', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/conservation', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/accessibility', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/local_tour_guides', locals: {f: f}  %>																
        <%= render partial: 'user/tourist_attraction_surveys/show/kindness', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/beauty', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/infrastructure', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/historical_importance', locals: {f: f}  %>																
        <%= render partial: 'user/tourist_attraction_surveys/show/artistic_importance', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/architectural_importance', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/natural_importance', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/cultural_importance', locals: {f: f}  %>																
        <%= render partial: 'user/tourist_attraction_surveys/show/economic_importance', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/interest', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/sort_order_by_destination', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/shopping', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/events', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/cultural_centers', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/historical_buildings', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/strong', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/churches', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/museums', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/parks', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/state_parks', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/national_parks', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/thematic_parks', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/tours', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/beaches', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/beach_tents', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/adventure_tourism', locals: {f: f}  %>
        <%= render partial: 'user/tourist_attraction_surveys/show/final', locals: {f: f}  %>
    </div>
  </div>
      
    <div class="card-footer">
      <%= link_to raw('<i class="far fa-window-close"></i> Voltar'), user_tourist_attraction_surveys_path(tourist_attraction_id: f.object.tourist_attraction_id), class: "btn btn-sm btn-danger" %>  
    </div>
        
    
<% end %>
    