config/routes.rb
Rails.application.routes.draw do
  
#  mount Ckeditor::Engine => '/ckeditor'
  mount LoldesignPublisher::Rails::Engine => '/'
  
  devise_for :admin, path_names: {
                                   sign_in: 'entrar',
                                   sign_out: 'sair'
                                 }

  devise_for :user, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }

  devise_for :customer, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }
  
                                        
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :cities, only: [:index] 


  namespace :admin do 

    resources :customers do
      collection do
        get :filters
      end
    end

    resources :booking_policies do
      collection do
        get :filters
      end
    end

    resources :rooms do
      collection do
        get :filters
      end
    end

    resources :occupations do
      collection do
        get :filters
      end
    end

    resources :accommodation_sizes do
      collection do
        get :filters
      end
    end

    resources :type_terms do
      collection do
        get :filters
      end
    end

    resources :terms do
      collection do
        get :filters
      end
    end

    resources :establishment_terms do
      collection do
        get :filters
      end
    end

    resources :type_attractions do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    
    resources :admins do
      collection do
        get :filters
      end
    end

    resources :commforts do
      collection do
        get :filters
      end
    end

    resources :price_ranges do
      collection do
        get :filters
      end
    end

    resources :payment_types do
      collection do
        get :filters
      end
    end
    resources :lodgings do
      collection do
        get :filters
      end
    end
    resources :services do
      collection do
        get :filters
      end
    end
    resources :accommodation_items do
      collection do
        get :filters
      end
    end
    resources :accommodation_types do
      collection do
        get :filters
      end
    end
    resources :environments do
      collection do
        get :filters
      end
    end
    resources :recreation_areas do
      collection do
        get :filters
      end
    end
    resources :rules do
      collection do
        get :filters
      end
    end
    resources :social_items do
      collection do
        get :filters
      end
    end

    resources :enterprises do
      collection do
        get :filters
      end
    end

    resources :structures do
      collection do
        get :filters
      end
    end


    resources :environments do
      collection do
        get :filters
      end
    end    

    resources :form_payments do
      collection do
        get :filters
      end
    end

    resources :recreation_areas do
      collection do
        get :filters
      end
    end

    resources :rules do
      collection do
        get :filters
      end
    end

    resources :services do
      collection do
        get :filters
      end
    end

    resources :social_items do
      collection do
        get :filters
      end
    end   

    resources :structures do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    resources :icons do
      collection do
        get :filters
      end
    end

    resources :furnitures do
      collection do
        get :furnitures
      end
    end

    resources :business_establishments do
      collection do
        get :filters
      end
    end

    resources :establishment_categories do
      collection do
        get :filters
      end
    
    end


    root :to => "services#index"

  end


  namespace :user do

    resources :chefs do
      collection do
        get :filters
      end
    end

    

    resources :restaurants do
      collection do
        get :filters
        get 'country'
      end
    end
    resources :restaurant_surveys do
      collection do
        get :filters
      end
    end

    
    resources :publications do
      collection do
        get :filters
      end
    end
    resources :establishments do
      collection do
        get :filters
        get 'city'
        get 'country'
        post 'address-infos'    , to: 'establishments#address_infos', as: :address_infos

      end
    end
    
    resources :main_courses do
      collection do
        get :filters
      end
    end    

    resources :users do
      collection do
        get :filters
      end
    end 
    resources :specialities do
      collection do
        get :filters
      end
    end   
    resources :tourist_attractions do
      collection do
        get :filters
        get 'country'
      end
    end   

    resources :tourist_attraction_surveys do
      collection do
        get :filters
      end
    end      

    resources :hotels do
      collection do
        get :filters
        get 'city'
        get 'country'
      end
    end       

    resources :hotel_surveys do
      collection do
        get :filters
      end
    end  

    resources :cities do 
      collection do
        get :filters
      end
    end


    root :to => "hotels#index"


  end

  namespace :customer do 
    resources :profiles, except: [:index, :new]
  end
end

app/models/icon.rb
class Icon < ApplicationRecord
	has_one_attached :image

	validates :name, :description, :business_establishment, presence: :true 

end

app/controllers/admin/icons_controller.rb
class Admin::IconsController < Admin::BaseController
  before_action :load_icon, only: [:show, :destroy, :edit, :update]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @icons = Icon.all.order('name').page(params[:page] || 1).per_page(30)
  end


  def new
    @icon = Icon.new
  end

  def create
    @icon = Icon.new(icon_params)

    if @icon.save
      redirect_to admin_icons_path, notice: "Registro #{@icon.name} Criado com sucesso"
    else
      render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
    end
  end

  def edit
    
  end

  def show
    @icon = Icon.find(params[:id])
  end


  def update
    if @icon.update(icon_params)
      redirect_to admin_icons_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @icon.active = @icon.active ? false : true
    if @icon.save
       redirect_to admin_icons_path, notice: @icon.active ? 'Registro ativado com sucesso' : 'Registro desativado com sucesso'
    end
  end
  def filters
    @icons  = Icon.order(created_at: :desc)
    @icons  = process_filters(params, @icons ) if params[:query].present?

    respond_to do |format|
      format.html do 
        @icons  = @icons.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :name, type: :common},
    ]
  end


  
  def load_icon
    @icon = Icon.find(params[:id])
  end

  def icon_params
    params
      .require(:icon)
      .permit(
        :name,
        :active,
        :description,
        :image,
        :order,
        business_establishment:[],
      )
  end
end

app/helpers/usuario/icons_helper.rb
module Usuario::IconsHelper
end

app/views/admin/icons/_form.html.erb
<%= simple_form_for [:admin, @icon], 
  wrapper_mappings: {
    check_boxes:    :vertical_collection,
    radio_buttons:  :vertical_collection,
    file:           :custom_file,
    boolean:        :custom_boolean_switch
  }  do |f|%>

  <section class='fields-wrapper two-columns'>
    <header>
      <h2>Novo Icone</h2>
    </header>
    <article>
      <%= f.label "Selecione a imagem do icone" %>
      <%= f.file_field :image %>
    </article>
    <article>
      <%= f.input :name, wrapper_html: {class: 'col-9'} %>      
      <%= f.input :description, wrapper_html: {class: 'col-9'} %>      
    </article>
    <article>
      <%= f.input :business_establishment, as: :check_boxes, collection: human_attribute_establishment_types, input_html: {multiple: true}, required: :true %>
      <%= f.input :active, wrapper_html: {class: 'col-9'} %>
    </article>
  </section>

  <footer>
    <%= cancel_action(path: admin_icons_path) %>
    <%= submit_button f %>
  </footer>
<% end %>

app/views/admin/icons/_icon.html.erb
<tr>
  <td><%= icon.name %></td>
  <td><%= icon.business_establishment %></td>
  <td><%= icon.active %></td>
  <td>
    <%= show_resource_with_icon admin_icon_path(icon) %>
    <%= edit_resource edit_admin_icon_path(icon) %>
    <% if icon.active == true %>
  <%= link_to raw('<i class="icon-cancel" style = "color:red"></i>'), admin_icon_path(icon),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% else %>
     
  <%= link_to raw('<i class="icon-check"style = "color:green"></i>'), admin_icon_path(icon),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
   <%end%>
  </td>
</tr>

app/views/admin/icons/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/icons/index.html.erb
<%= title_page "Icones" %>

<%= add_resource "Icone", new_admin_icon_path %>
<%= render partial: 'layouts/filters', locals: { path: filters_admin_icons_path, resource: Icon } %>


<table class="table-page">
  <thead>
    <tr>
      <th><%= Icon.human_attribute_name(:name) %></th>
      <th><%= Icon.human_attribute_name(:business_establishment) %></th>
      <th><%= Icon.human_attribute_name(:active) %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <%= display_list_for(@icons, fields: 4) %>
  </tbody>
</table>

<%= will_paginate @icons %>

app/views/admin/icons/new.html.erb
<%= render partial: 'form' %>

app/views/admin/icons/show.html.erb
<br>
<section class='fields-wrapper two-columns'>
    <header>
      	<h2> <%= "Icone #{@icon.name} " %> 
      		<%= edit_resource edit_admin_icon_path(@icon) %>
      	</h2>
    </header>
</section>
  <section class='fields-wrapper two-columns'>    
      <article>
            <br>
            <b><%= Icon.human_attribute_name(:name) %>:&nbsp;</b>
            <%= @icon.name %><br>
            <b><%= Icon.human_attribute_name(:description) %>:&nbsp;</b>
            <%= @icon.description %><br>

            
      </article>
  </section>

  <footer>
    <%= cancel_action(path: admin_furnitures_path) %>
  </footer>