config/routes.rb
Rails.application.routes.draw do
  
#  mount Ckeditor::Engine => '/ckeditor'
  mount LoldesignPublisher::Rails::Engine => '/'
  
  devise_for :admin, path_names: {
                                   sign_in: 'entrar',
                                   sign_out: 'sair'
                                 }

  devise_for :user, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }

  devise_for :customer, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }
  
                                        
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :cities, only: [:index] 


  namespace :admin do 

    resources :customers do
      collection do
        get :filters
      end
    end

    resources :booking_policies do
      collection do
        get :filters
      end
    end

    resources :rooms do
      collection do
        get :filters
      end
    end

    resources :occupations do
      collection do
        get :filters
      end
    end

    resources :accommodation_sizes do
      collection do
        get :filters
      end
    end

    resources :type_terms do
      collection do
        get :filters
      end
    end

    resources :terms do
      collection do
        get :filters
      end
    end

    resources :establishment_terms do
      collection do
        get :filters
      end
    end

    resources :type_attractions do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    
    resources :admins do
      collection do
        get :filters
      end
    end

    resources :commforts do
      collection do
        get :filters
      end
    end

    resources :price_ranges do
      collection do
        get :filters
      end
    end

    resources :payment_types do
      collection do
        get :filters
      end
    end
    resources :lodgings do
      collection do
        get :filters
      end
    end
    resources :services do
      collection do
        get :filters
      end
    end
    resources :accommodation_items do
      collection do
        get :filters
      end
    end
    resources :accommodation_types do
      collection do
        get :filters
      end
    end
    resources :environments do
      collection do
        get :filters
      end
    end
    resources :recreation_areas do
      collection do
        get :filters
      end
    end
    resources :rules do
      collection do
        get :filters
      end
    end
    resources :social_items do
      collection do
        get :filters
      end
    end

    resources :enterprises do
      collection do
        get :filters
      end
    end

    resources :structures do
      collection do
        get :filters
      end
    end


    resources :environments do
      collection do
        get :filters
      end
    end    

    resources :form_payments do
      collection do
        get :filters
      end
    end

    resources :recreation_areas do
      collection do
        get :filters
      end
    end

    resources :rules do
      collection do
        get :filters
      end
    end

    resources :services do
      collection do
        get :filters
      end
    end

    resources :social_items do
      collection do
        get :filters
      end
    end   

    resources :structures do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    resources :icons do
      collection do
        get :filters
      end
    end

    resources :furnitures do
      collection do
        get :furnitures
      end
    end

    resources :business_establishments do
      collection do
        get :filters
      end
    end

    resources :establishment_categories do
      collection do
        get :filters
      end
    
    end


    root :to => "services#index"

  end


  namespace :user do

    resources :chefs do
      collection do
        get :filters
      end
    end

    

    resources :restaurants do
      collection do
        get :filters
        get 'country'
      end
    end
    resources :restaurant_surveys do
      collection do
        get :filters
      end
    end

    
    resources :publications do
      collection do
        get :filters
      end
    end
    resources :establishments do
      collection do
        get :filters
        get 'city'
        get 'country'
        post 'address-infos'    , to: 'establishments#address_infos', as: :address_infos

      end
    end
    
    resources :main_courses do
      collection do
        get :filters
      end
    end    

    resources :users do
      collection do
        get :filters
      end
    end 
    resources :specialities do
      collection do
        get :filters
      end
    end   
    resources :tourist_attractions do
      collection do
        get :filters
        get 'country'
      end
    end   

    resources :tourist_attraction_surveys do
      collection do
        get :filters
      end
    end      

    resources :hotels do
      collection do
        get :filters
        get 'city'
        get 'country'
      end
    end       

    resources :hotel_surveys do
      collection do
        get :filters
      end
    end  

    resources :cities do 
      collection do
        get :filters
      end
    end


    root :to => "hotels#index"


  end

  namespace :customer do 
    resources :profiles, except: [:index, :new]
  end
end

app/views/admin/admins/_admin.html.erb
<tr>
	<td><%= admin.name %></td>
	<td><%= admin.email %></td>
	<td><%= admin.phone_number %></td>    
	<td>
		<%= show_resource_with_icon admin_admin_path(admin) %>
		<%= edit_resource edit_admin_admin_path(admin) %>
		<%= remove_resource(admin_admin_path(admin), {})%>
	</td>
</tr>

app/views/admin/admins/_form.html.erb
<%= simple_form_for [:admin, @admin] do |f| %>

  <section class='fields-wrapper two-columns'>
    <header>
      <h2>Administrador</h2>
    </header>
    <article>
      <%= f.label "Foto do Usuário" %>
      <%= f.file_field :photo %>
    </article>
    <article>
      <%= f.input :name, wrapper_html: {class: 'col-9'} %>      
      <%= f.input :phone_number, wrapper_html: {class: 'col-9'} %>      
      <%= f.input :email, wrapper_html: {class: 'col-9'} %>      
    </article>
    <article>
      <%= f.input :password, wrapper_html: {class: 'col-9'} %>
      <%= f.input :password_confirmation, wrapper_html: {class: 'col-9'} %>
    </article>
  </section>

  <footer>
    <%= cancel_action(path: admin_admins_path) %>
    <%= submit_button f %>
  </footer>
<% end %>

app/views/admin/admins/_show_admin.html.erb
	<section class='fields-wrapper two-columns'>
		<header>
			<h2>Administrador</h2>
		</header>
		<article>
			<% if @admin.photo.attached? %>
					<%= image_tag(@admin.photo, class: "mr-3") %>
			<% else %>
					<%= image_tag 'people-default.png', resize: "100x150>", class: "mr-3" %>
			<% end %>
		</article>    
		<article>
			<b><%= Admin.human_attribute_name(:name) %>:&nbsp;</b>
			<%= @admin.name %><br />      
			<b><%= Admin.human_attribute_name(:email) %>:&nbsp;</b>
			<%= @admin.email %><br />            
			<b><%= Admin.human_attribute_name(:phone_number) %>:&nbsp;</b>
			<%= @admin.phone_number %><br />            
		</article>
		
	</section>

	<footer>
		<%= cancel_action(path: admin_admins_path) %>
	</footer>

app/views/admin/admins/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/admins/index.html.erb
<%= title_page "Administradores" %><%= add_resource "Administrador", new_admin_admin_path %><%= render partial: 'layouts/filters', locals: { path: filters_admin_admins_path, resource: Admin } %><table class='table-page'>  <thead>    <tr>      <th><%= Admin.human_attribute_name(:name) %></th>		<th><%= Admin.human_attribute_name(:email) %></th>      <th><%= Admin.human_attribute_name(:phone_number) %></th>      <th>&nbsp;</th>    </tr>  </thead>  <tbody>    <%= display_list_for(@admins, fields: 4) %>  </tbody></table><%= will_paginate @admins %>

app/views/admin/admins/new.html.erb
<%= render partial: 'form' %>

app/views/admin/admins/show.html.erb
<%= render partial: 'show_admin' %>