config/routes.rb
Rails.application.routes.draw do
  
#  mount Ckeditor::Engine => '/ckeditor'
  mount LoldesignPublisher::Rails::Engine => '/'
  
  devise_for :admin, path_names: {
                                   sign_in: 'entrar',
                                   sign_out: 'sair'
                                 }

  devise_for :user, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }

  devise_for :customer, path_names: {
                                       sign_in: 'entrar',
                                       sign_out: 'sair',
                                       edit: 'editar'
                                     }
  
                                        
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :cities, only: [:index] 


  namespace :admin do 

    resources :customers do
      collection do
        get :filters
      end
    end

    resources :booking_policies do
      collection do
        get :filters
      end
    end

    resources :rooms do
      collection do
        get :filters
      end
    end

    resources :occupations do
      collection do
        get :filters
      end
    end

    resources :accommodation_sizes do
      collection do
        get :filters
      end
    end

    resources :type_terms do
      collection do
        get :filters
      end
    end

    resources :terms do
      collection do
        get :filters
      end
    end

    resources :establishment_terms do
      collection do
        get :filters
      end
    end

    resources :type_attractions do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    
    resources :admins do
      collection do
        get :filters
      end
    end

    resources :commforts do
      collection do
        get :filters
      end
    end

    resources :price_ranges do
      collection do
        get :filters
      end
    end

    resources :payment_types do
      collection do
        get :filters
      end
    end
    resources :lodgings do
      collection do
        get :filters
      end
    end
    resources :services do
      collection do
        get :filters
      end
    end
    resources :accommodation_items do
      collection do
        get :filters
      end
    end
    resources :accommodation_types do
      collection do
        get :filters
      end
    end
    resources :environments do
      collection do
        get :filters
      end
    end
    resources :recreation_areas do
      collection do
        get :filters
      end
    end
    resources :rules do
      collection do
        get :filters
      end
    end
    resources :social_items do
      collection do
        get :filters
      end
    end

    resources :enterprises do
      collection do
        get :filters
      end
    end

    resources :structures do
      collection do
        get :filters
      end
    end


    resources :environments do
      collection do
        get :filters
      end
    end    

    resources :form_payments do
      collection do
        get :filters
      end
    end

    resources :recreation_areas do
      collection do
        get :filters
      end
    end

    resources :rules do
      collection do
        get :filters
      end
    end

    resources :services do
      collection do
        get :filters
      end
    end

    resources :social_items do
      collection do
        get :filters
      end
    end   

    resources :structures do
      collection do
        get :filters
      end
    end

    resources :users do
      collection do
        get :filters
      end
    end
    resources :icons do
      collection do
        get :filters
      end
    end

    resources :furnitures do
      collection do
        get :furnitures
      end
    end

    resources :business_establishments do
      collection do
        get :filters
      end
    end

    resources :establishment_categories do
      collection do
        get :filters
      end
    
    end


    root :to => "services#index"

  end


  namespace :user do

    resources :chefs do
      collection do
        get :filters
      end
    end

    

    resources :restaurants do
      collection do
        get :filters
        get 'country'
      end
    end
    resources :restaurant_surveys do
      collection do
        get :filters
      end
    end

    
    resources :publications do
      collection do
        get :filters
      end
    end
    resources :establishments do
      collection do
        get :filters
        get 'city'
        get 'country'
        post 'address-infos'    , to: 'establishments#address_infos', as: :address_infos

      end
    end
    
    resources :main_courses do
      collection do
        get :filters
      end
    end    

    resources :users do
      collection do
        get :filters
      end
    end 
    resources :specialities do
      collection do
        get :filters
      end
    end   
    resources :tourist_attractions do
      collection do
        get :filters
        get 'country'
      end
    end   

    resources :tourist_attraction_surveys do
      collection do
        get :filters
      end
    end      

    resources :hotels do
      collection do
        get :filters
        get 'city'
        get 'country'
      end
    end       

    resources :hotel_surveys do
      collection do
        get :filters
      end
    end  

    resources :cities do 
      collection do
        get :filters
      end
    end


    root :to => "hotels#index"


  end

  namespace :customer do 
    resources :profiles, except: [:index, :new]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	
before_action :load_user, only: [:show, :destroy, :edit, :update]
before_action :load_filter_fields, only: [:index, :filters]
	

  def index
    @users = User.all.order('email').page(params[:page] || 1).per_page(30)
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_users_path, notice: 'Criado com sucesso'
    else
      render action: :new
    end
  end

  def edit
    
  end

  def show
    @user = User.find(params[:id])
  end


  def update

    if params[:user][:password].present?
      if @user.update(user_params_without_password)
        redirect_to user_users_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit
      end        
    elsif params[:user][:profile_id].present?
      if @user.update_attributes(user_params_without_profile)
        redirect_to user_users_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit
      end
    else
      if @user.update_attributes(user_params)
        redirect_to user_users_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit
      end
    end

  end

  def destroy
    @user.destroy

    redirect_to user_users_path, notice: 'Removido com sucesso'
  end


  def filters
    @users = User.order(created_at: :desc)
    @users = process_filters(params, @users) if params[:query].present?

    respond_to do |format|
      format.html do 
        @users = @users.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :email, type: :common},
    ]
  end

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params
      .require(:user)
      .permit(
        :email,
        :password,
        :password_confirmation,
        :name,
        :phone_number,
        :photo
      )
  end

  def user_params_without_password
    params
      .require(:user)
      .permit(
        :email,
        :name,
        :phone_number,
        :photo
      )
  end

  def user_params_without_profile
    params
      .require(:user)
      .permit(
        :email,
        :password,
        :password_confirmation,
        :name,
        :phone_number,
        :photo     
      )
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  layout "reporter"
  before_action :authenticate_user!
  

  def authenticated_user
    current_user
  end

   
 def process_filters(params, resources)
    @resources = resources

    filters_groups = @filters_arr.group_by{ |filter| filter[:type] }
    filter_by_type filters_groups

    @resources
  end

  def filter_by_type filter
    filter_commons  filter[:common] if filter[:common].present?
    filter_nesteds  filter[:nested] if filter[:nested].present?
    filter_commons  filter[:select] if filter[:select].present?
    filter_dates    filter[:date]   if filter[:date].present?
    filter_floats   filter[:float]  if filter[:float].present?
  end

  def filter_commons commons
    commons.each do |common|
      @resources = @resources.where("LOWER (#{common[:attr].to_s}) LIKE LOWER(?)"  , "%#{params[:query][common[:attr]]}%") if params[:query][common[:attr]].present?      
    end 
  end

  def filter_dates dates
    dates.each do |date|
      @resources = @resources.where(date[:attr] => [params[:query][date[:attr]][:from].to_date.beginning_of_day..params[:query][date[:attr]][:to].to_date.end_of_day]) if params[:query][date[:attr]].present? && params[:query][date[:attr]][:to].present? && params[:query][date[:attr]][:from].present?
    end
  end

  def filter_nesteds nesteds
    nesteds.each do |nested|
      @resources = @resources.joins(nested[:nested_class]).where("LOWER(#{nested[:nested_class].to_s.pluralize}.#{nested[:nested_attr]}) LIKE LOWER(?)", "%#{params[:query][nested[:attr]]}%") if params[:query][nested[:attr]].present?
    end
  end

  def filter_floats floats
    floats.each do |float|
      @resources = @resources.where(float[:attr] => params[:query][float[:attr]].to_f) if params[:query][float[:attr]].present?
    end
  end

end

app/controllers/user/chefs_controller.rb
class User::ChefsController < User::BaseController

  before_action :load_chef, only: [:show, :destroy, :edit, :update]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @chefs = Chef.all.order('name').page(params[:page] || 1).per_page(30)
  end


  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)

    if @chef.save
      redirect_to user_chefs_path, notice: "Registro #{@chef.name} Criado com sucesso"
    else
      render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
    end
  end

  def edit
    
  end

  def show
    @chef = Chef.find(params[:id])
  end


  def update
    if @chef.update_attributes(chef_params)
       @chef = Chef.find(params[:id])
      redirect_to user_chefs_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @chef.active = false
    if @chef.save
       redirect_to user_chefs_path, notice: 'Registro desativado com sucesso'
    end
  end
  def filters
    @chefs  = Chef.order(created_at: :desc)
    @chefs  = process_filters(params, @chefs ) if params[:query].present?

    respond_to do |format|
      format.html do 
        @chefs  = @chefs.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :name, type: :common},
    ]
  end


  
  def load_chef
    @chef = Chef.find(params[:id])
  end

  def chef_params
    params
      .require(:chef)
      .permit(
        :name,
        :active,
        :description,
        :service_time,
        main_courses:[],
        photos:[],
        videos: [],
      )
  end
end

app/controllers/user/cities_controller.rb
class User::CitiesController < User::BaseController

  before_action :load_city, only: [:show, :destroy, :edit, :update]
  before_action :load_hotels, only: [:index, :filters]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @cities = City.order(:created_at).page(params[:page] || 1).per_page(30)
    
  end


  def new
    @city = City.new
    @city.build_establishment

  end

  def create
    @city = City.new(city_params)

    createCityManager = EstablishmentsManager.new()
    city_existes = createCityManager.process(@city.country, @city.state, @city.city, "validate")

    if @city.save && !city_existes
      redirect_to user_cities_path, notice: "Registro Criado com sucesso"
    else
      if city_existes
        redirect_to user_cities_path, notice: 'A cidade já está cadatrado.'
      else
        render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
      end 
    end
  end

  def edit

  end

  def show
    city = City.find(params[:id])
  end


  def update

    if @city.update_attributes(city_params)
      redirect_to user_cities_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @city.active = false
    if @city.save
     redirect_to user_cities_path, notice: 'Registro desativado com sucesso'
   end
 end
 def filters
  @cities  = City.order(created_at: :desc)
  @cities  = process_filters(params, @cities ) if params[:query].present?

  respond_to do |format|
    format.html do 
      @cities  = @cities.page(params[:page] || 1).per_page(30)
      render :index
    end
  end
end

private

def load_city
  @city = City.find(params[:id])
end

def load_filter_fields
  @filters_arr = [
    {attr: :city, type: :common},    
    {attr: :state, type: :common},
    {attr: :country, type: :common},
    {attr: :biome, type: :common},
    {attr: :region, type: :common},
  ]
end

def load_hotels
  
end

def load_restaurants

end
def load_touristattractions

end


def city_params
  params
  .require(:city)
  .permit(
    :text_apresentation,
    :best_time,
    :how_find,
    :city,
    :state,
    :country,
    :biome,
    :perfect_day,
    :special,
    :perfect_day_remarks,
    :region,
    :establishment_id,
    :best_experiences,
    differentials:[],
    photos:[],
    videos: [],
    documents: [], 
    establishment_attributes: [
      :id,
      :name,
      :active,
      :environment,
      :neighborhood,
      :comfort_classification,
      :final_comment,
      :contact,
      :email,
      :address,
      :cep,
      :street,
      :complement,
      :number_address,
      :city,
      :state,
      :nationality,
      :final_note,
      :geolocalization,
      :reference_point,
      :owner,
      :telephone,
      :reservation_phone,
      :comments,
      :business_establishment,
      :facebook,
      :linkedin,
      :twitter,
      :instagram,
      :website],
      )
end
end

app/controllers/user/establishments_controller.rb
class User::EstablishmentsController < User::BaseController
  before_action :load_establishment, except: [:address_infos, :destroy]
  before_action :load_filter_fields, only: [:index, :filters]


  def index
    @establishments = Establishment.all.order('updated_at').page(params[:page] || 1).per_page(30)
  end


  def new
    @establishment = Establishment.new
  end

  def create
    @establishment = Establishment.new(establishment_params)

    if @establishment.save

      redirect_to user_establishments_path, notice: "Registro #{@establishment.name} Criado com sucesso"
    else
      render action: :new, notice: 'Um erro ocorreu durante a gravação do registro, verifique os campos e tente novamente.'
    end
  end

  def edit
    
  end

  def show
    @establishment = Establishment.find(params[:id])
  end


  def update
    
    if @establishment.update_attributes(establishment_params)
      
      redirect_to user_establishments_path, notice: 'Atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def destroy
    @establishment.active = false
    if @establishment.save
      
      redirect_to user_establishments_path, notice: 'Registro desativado com sucesso'
    end
  end

  def address_infos
    manager = CepManager.new(params[:cep])

    begin
      manager = manager.process
      render status: 200, json: manager.to_json
    rescue
      render status: 422
    end
  end


  def filters
    @establishments  = Establishment.order(created_at: :desc)
    @establishments  = process_filters(params, @establishments ) if params[:query].present?

    respond_to do |format|
      format.html do 
        @establishments  = @establishments.page(params[:page] || 1).per_page(30)
        render :index
      end
    end
  end
  
  private

  def load_filter_fields
    @filters_arr = [
      {attr: :name, type: :common},
    ]
  end


  
  def load_establishment
    @establishment = Establishment.find(params[:id])
  end

  def establishment_params
    params
      .require(:establishment)
      .permit(
        :name,
        :active,
        :environment,
        :comfort_classification,
        :final_comment,
        :contact,
        :email,
        :address,
        :cep,
        :street,
        :complement,
        :number_address,
        :city,
        :state,
        :nationality,
        :final_note,
        :geolocalization,
        :reference_point,
        :owner,
        :telephone,
        :reservation_phone,
        :comments,
        :facebook,
        :linkedin,
        :twitter,
        :instagram,
        :website,
        business_establishment: [],
      )
  end
end
require 'correios-cep'

app/controllers/user/home_controller.rb
class User::HomeController < User::BaseController

	def index
		
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/user/establishments/_establishment.html.erb
    <div class="row text-center">

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          
    <% if establishment.hotels.first.photos.attached? %>
          <%= image_tag(establishment.hotels.photos.first, resize: "100x150", class: "card-img-top") %>
      <% else %>
          <%= image_pack_tag 'restaurant_default.png', resize: "100x150", class: "card-img-top" %>
      <% end %>



          <div class="card-body">
            <h4 class="card-title"><%= establishment.name %></h4>
            <p class="card-text">establishment.comments </p>
          </div>
          <div class="card-footer">
            <div class="btn-group">

            <%= link_to 'Mostrar', user_establishment_path(establishment),class: "btn btn-success" %>
            <%= link_to 'Editar', edit_user_establishment_path(establishment),class: "btn btn-info" %>
            <%= link_to 'Inativar', user_establishment_path(establishment),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>


            </div>
          </div>
        </div>
      </div>
    </div>

app/views/user/establishments/_form.html.erb
<%= simple_form_for [:user, @establishment], 
  wrapper_mappings: {
    check_boxes:    :vertical_collection,
    radio_buttons:  :vertical_collection,
    file:           :custom_file,
    boolean:        :custom_boolean_switch
  }  do |f|%>
  <%= f.error_notification %>
    
  <%
    require 'json'
    finder = Correios::CEP::AddressFinder.new
  %>
    <div class="container-md">
      <div class="card md-4">
        <div class="card-body">
    
          <h4>Cadastro de Restaurantes </h4>
          <p>Preencha as informaações do Restaurante que está avaliando</p>

          <%= f.input :business_establishment,  collection: human_attribute_establishment_types  %>
          <%= f.input :name, placeholder: 'Nome do estabelecimento ', required: :true %>
          <%= f.input :environment, placeholder: 'Ponto de referencia do estabelecimento  ', required: :true %>
          <%= f.input :comfort_classification, placeholder: 'Ponto de referencia do estabelecimento  ', required: :true %>
          <%= f.input :contact, placeholder: 'Contato do estabelecimento ', required: :true %>
          <%= f.input :email, placeholder: 'Email do estabelecimento  ', required: :true %>
          <%= f.input :address, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :cep, placeholder: 'Endereço do estabelecimento  ', required: :true, input_html: { value: '06327320' } %>
          <%= f.input :street, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :complement, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :number_address, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :state, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :nationality, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :city, placeholder: 'Endereço do estabelecimento  ', required: :true %>
          <%= f.input :final_note, placeholder: 'Nota Final do estabelecimento ', required: :true %>
          <%= f.input :geolocalization, placeholder: 'Localização do estabelecimento  ', required: :true %>
          <%= f.input :reference_point, placeholder: 'Ponto de referencia do estabelecimento  ', required: :true %>
          <%= f.input :owner, placeholder: 'Dono do estabelecimento  ', required: :true %>
          <%= f.input :telephone, placeholder: 'Telefone do estabelecimento  ', required: :true %>
          <%= f.input :reservation_phone, placeholder: 'Telefone reserva do estabelecimento  ', required: :true %>
          <%= f.input :comments, placeholder: 'Comentario sobre o estabelecimento  ', required: :true %>
          <%= f.input :final_comment, placeholder: 'Descriçao do item', required: :true %>
          <%= f.input :business_establishment, as: :check_boxes, collection: human_attribute_establishment_types, input_html: {multiple: true} %>
           

          <% 
              address = finder.get('06327320')
              teste = address
              teste[:city]
           %> 
          <%= f.input :active, as: :radio_buttons, required: :true, boolean_style: :inline  %>    
          <div class="btn-group">
            <%= f.button :submit ,"Gravar" , class: "btn -btn-primary"   %>
            <%= f.button :button, "Cancelar", type: "reset", class: "btn btn-danger" %>    
          </div>          


        </div>
      </div>
    </div>

<% end %>

app/views/user/establishments/edit.html.erb
<%= render partial: 'form' %>

app/views/user/establishments/index.html.erb
<div class="panel-group">

	<div class="panel panel-default">
		<div class="panel-heading">
			<%= render partial: 'layouts/filters/filters', locals: { path: filters_user_establishments_path, resource: Establishment } %>

		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<%= link_to "Novo", new_user_establishment_path, class: "btn btn-primary" %>
		</div>
		<div class="panel-body"><%= display_list_for(@establishments, fields: 20) %></div>
		<div class="panel-footer"><%= will_paginate @establishments %></div>
	</div>
</div>

app/views/user/establishments/new.html.erb
<%= render partial: 'form' %>

app/views/user/establishments/show.html.erb
<div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="row justify-content-center mb-3">
        <div class="card mb-4">
          <div class="card-body">
          	<h4> <%= "Estabelecimento #{@establishment.name} " %> 
                <%= edit_resource edit_user_establishment_path(@establishment) %>
  	         </h4>
           <br>
            <b><%= Establishment.human_attribute_name(:active) %>:&nbsp;</b>
            <%= @establishment.active %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:environment) %>:&nbsp;</b>
            <%= @establishment.environment %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:comfort_classification) %>:&nbsp;</b>
            <%= @establishment.comfort_classification %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:final_comment) %>:&nbsp;</b>
            <%= @establishment.final_comment %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:contact) %>:&nbsp;</b>
            <%= @establishment.contact %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:email) %>:&nbsp;</b>
            <%= @establishment.email %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:address) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:cep) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:street) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:complement) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:number_address) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:city) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:state) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <br>
            <b><%= Establishment.human_attribute_name(:nationality) %>:&nbsp;</b>
            <%= @establishment.address %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:name) %>:&nbsp;</b>
            <%= @establishment.name %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:final_note) %>:&nbsp;</b>
            <%= @establishment.final_note %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:geolocalization) %>:&nbsp;</b>
            <%= @establishment.geolocalization %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:reference_point) %>:&nbsp;</b>
            <%= @establishment.reference_point %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:owner) %>:&nbsp;</b>
            <%= @establishment.owner %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:telephone) %>:&nbsp;</b>
            <%= @establishment.telephone %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:reservation_phone) %>:&nbsp;</b>
            <%= @establishment.reservation_phone %><br>
            <br>
            <b><%= Establishment.human_attribute_name(:comments) %>:&nbsp;</b>
            <%= @establishment.comments %><br>
            <br>
            <%= link_to "Voltar", user_establishments_path, class: "btn btn-secondary"%>
        </div>
      </div>
    </div>
  </div>
</div>    